services:
  - type: web
    name: resume-analysis-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm run install:backend
    startCommand: npm run start:backend
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: resume-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: resume-db
    region: oregon
    ipAllowList: []  # You'll need to add your IP or set to [] for full access
    plan: free 